DESTDIR?=	/usr/local
NAGIOS_PLUGINS_DIR?=	${DESTDIR}/libexec/nagios
RUBY?=	/usr/local/bin/ruby

all:	check_resque

check_resque:
	sed -e "s|__RUBY__|${RUBY}|" check_resque.rb > ${.TARGET} || (rm -f ${.TARGET} && exit 1)

install:
	install check_resque ${NAGIOS_PLUGINS_DIR}/

clean:
	rm -f check_resque
